name: hallo_doctor_client
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.1
  flutter:
    sdk: flutter
  cloud_firestore: ^3.1.6
  firebase_auth: ^3.3.5
  firebase_messaging: ^11.2.10
  firebase_core: ^1.11.0
  firebase_storage: ^10.2.5
  cloud_functions: ^3.2.5
  firebase_database: ^9.0.5
  google_sign_in: ^5.1.1
  flutter_signin_button: ^2.0.0
  flutter_easyloading: ^3.0.3
  fluttertoast: ^8.0.8
  google_fonts: ^2.1.0
  carousel_slider: ^4.0.0
  flutter_rating_bar: ^4.0.0
  string_validator: ^0.3.0
  image_picker: ^0.8.4+4
  path_provider: ^2.0.6
  path: ^1.8.0
  flutter_dotenv: ^5.0.2
  cached_network_image: ^3.1.0+1
  date_picker_timeline: ^1.2.3
  flutter_stripe: ^2.1.0
  flutter_svg: ^1.0.2
  lottie: ^1.2.1
  http: ^0.13.4
  rounded_loading_button: ^2.0.9
  flutter_form_builder: ^7.0.0
  form_builder_validators: ^7.2.0
  package_info_plus: ^1.3.0
  open_file: ^3.2.1
  file_picker: ^4.4.0
  uuid: ^3.0.6
  mime: ^1.0.1
  flutter_chat_ui:
    git: https://github.com/amsyary/flutter_chat_ui.git
  flutter_firebase_chat_core:
    git: https://github.com/amsyary/flutter_firebase_chat_core.git
  flutter_local_notifications: ^9.4.0
  timezone: ^0.8.0
  flutter_native_timezone: ^2.0.0
  jiffy: ^5.0.0
  agora_rtc_engine: ^5.1.0
  permission_handler: ^9.2.0
  flutter_callkit_incoming: ^1.0.1+8

dev_dependencies:
  flutter_lints: ^1.0.0
  lints: 1.0.1
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  change_app_package_name: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/icons/
    - assets/animations/

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/ic_launcher.png"
